/// Flutter icons IconPack
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';

  static const IconData priority_icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData question_mark = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData reset = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData save = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData send = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData settings = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData timer = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData todo = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData trash = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData view = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData zoom_in = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData zoom_out = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData add = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData board = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData bulb = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData calendar = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData carret_backward = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData carret_down = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData carret_foward = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData carret_up = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData chart = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData clock = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData close = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData dots_horizontal = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData dots_vertical = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData duplicate = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData effort_icon = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData feedback = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData filter_icon = const IconData(0xe824, fontFamily: _kFontFam);
  static const IconData folder = const IconData(0xe825, fontFamily: _kFontFam);
  static const IconData goal = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData house = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData inbox = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData info = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData keyword = const IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData label = const IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData list = const IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData login = const IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData menu_line = const IconData(0xe830, fontFamily: _kFontFam);
  static const IconData microphone = const IconData(0xe832, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe833, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe835, fontFamily: _kFontFam);
}
